# ========================
# æœºåœºèŠ‚è®¢é˜…
# ========================
proxy-providers:
 proxy-providers:
  Airport1:
    url: "https://sub01.fkknet.cn/api/v1/client/subscribe?token=4b2ac65f47f73956f77c42b07f6b08e7"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
    #override:
      #additional-prefix: "å‰ç¼€ |"
      #additional-suffix: "| åç¼€"
  Airport2:
    url: "https://106.55.228.246:36666/hxvip?token=afbc20e0cf47b2bb407a10b11d2ec098"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
    #override:
      #additional-prefix: "å‰ç¼€ |"
      #additional-suffix: "| åç¼€"

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# ========================
# ç«¯å£è®¾ç½®
# ========================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895

allow-lan: true
bind-address: "*"
mode: rule
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 30
log-level: info
profile:
  store-selected: true
  store-fake-ip: true

# ========================
# æ§åˆ¶é¢æ¿
# ========================
external-controller: 0.0.0.0:9090
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
secret: ""

# ========================
# DNS è®¾ç½®
# ========================
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  prefer-h3: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.20.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:Private / Domain,China / Domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5 
  proxy-server-nameserver:
    - 127.0.0.1:5336
  
 
ipv6: true
# ========================
# tun è®¾ç½®
# ========================
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
 
# ========================
# ç­–ç•¥ç»„
# ========================

pr: &pr
  type: select
  proxies:
  - é¦™æ¸¯-è‡ªåŠ¨
  - é¦™æ¸¯-æ‰‹åŠ¨   
  - é¦™æ¸¯-æ•…è½¬
  - å°æ¹¾-è‡ªåŠ¨
  - å°æ¹¾-æ‰‹åŠ¨
  - å°æ¹¾-æ•…è½¬
  - æ–°åŠ å¡-è‡ªåŠ¨
  - æ–°åŠ å¡-æ‰‹åŠ¨
  - æ–°åŠ å¡-æ•…è½¬
  - ç¾å›½-è‡ªåŠ¨
  - ç¾å›½-æ‰‹åŠ¨
  - ç¾å›½-æ•…è½¬
  - æ—¥æœ¬-è‡ªåŠ¨
  - æ—¥æœ¬-æ‰‹åŠ¨
  - æ—¥æœ¬-æ•…è½¬
  - éŸ©å›½-è‡ªåŠ¨
  - éŸ©å›½-æ‰‹åŠ¨
  - éŸ©å›½-æ•…è½¬  
  - ç›´è¿
  - æ‹’ç»
  
# ========================
# è§„åˆ™åŒ¹é…
# ========================
proxy-groups:
  - {name: GitHub, <<: *pr}
  - {name: Telegram, <<: *pr}
  - {name: YouTube, <<: *pr}
  - {name: Google, <<: *pr}
  - {name: Google-play, <<: *pr}  
  - {name: GoogleVoice, <<: *pr}
  - {name: Twitter, <<: *pr}
  - {name: Netflix, <<: *pr}
  - {name: cloudflare, <<: *pr}
  - {name: speedtest, <<: *pr}
  - {name: Block, <<: *pr}
  - {name: å›½å¤–, <<: *pr}
  - {name: å›½å†…, <<: *pr}
  - {name: å…¶ä»–, <<: *pr}

#é¦™æ¸¯ç»„
  - name: é¦™æ¸¯-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
  
  - name: é¦™æ¸¯-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
  
  - name: é¦™æ¸¯-æ•…è½¬
    type: fallback    
    interval: 300
    lazy: false
    proxies:
      - é¦™æ¸¯-æ‰‹åŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨      

#å°æ¹¾ç»„
  - name: å°æ¹¾-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"
  
  - name: å°æ¹¾-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"
  
  - name: å°æ¹¾-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - å°æ¹¾-æ‰‹åŠ¨
      - å°æ¹¾-è‡ªåŠ¨     

#æ–°åŠ å¡ç»„
  - name: æ–°åŠ å¡-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"
  
  - name: æ–°åŠ å¡-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"
  
  - name: æ–°åŠ å¡-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - æ–°åŠ å¡-æ‰‹åŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨      
 
#ç¾å›½ç»„
  - name: ç¾å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  
  - name: ç¾å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  
  - name: ç¾å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ç¾å›½-æ‰‹åŠ¨
      - ç¾å›½-è‡ªåŠ¨       
   
#æ—¥æœ¬ç»„
  - name: æ—¥æœ¬-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  
  - name: æ—¥æœ¬-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  
  - name: æ—¥æœ¬-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - æ—¥æœ¬-æ‰‹åŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨      

#éŸ©å›½ç»„
  - name: éŸ©å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 30
    interval: 300
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"
  
  - name: éŸ©å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"
  
  - name: éŸ©å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - éŸ©å›½-æ‰‹åŠ¨
      - éŸ©å›½-è‡ªåŠ¨         
    
# ========================
# è·¯ç”±
# ========================
rules:
 
  - RULE-SET,speedtest / Domain,speedtest
  - RULE-SET,Block / Domain,Block
  - RULE-SET,Github / Domain,GitHub
  - RULE-SET,Telegram / Domain,Telegram
  - RULE-SET,Telegram / IP,Telegram,no-resolve
  - RULE-SET,Youtube / Domain,YouTube
  - RULE-SET,Twitter / Domain,Twitter
  - RULE-SET,Google / Domain,Google
  - RULE-SET,Netflix / Domain,Netflix
  - RULE-SET,Netflix / IP,Netflix,no-resolve
  - RULE-SET,Google / IP,Google,no-resolve
  - RULE-SET,Google-play / Domain,Google-play
  - RULE-SET,GoogleVoice / Domain,GoogleVoice
  - RULE-SET,cloudflare / Domain,cloudflare
  - RULE-SET,Proxy / Domain,å›½å¤–
  - RULE-SET,Globe / Domain,å›½å¤–
  - RULE-SET,ChinaMedia / Domain,å›½å†…
  - RULE-SET,Direct / Domain,å›½å†…  
  - RULE-SET,China / Domain,å›½å†…
  - RULE-SET,China / IP,å›½å†…,no-resolve
  - RULE-SET,Private / Domain,å›½å†…
  - MATCH,å…¶ä»–
  
# ========================
# è§„åˆ™é›†
# ========================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  
rule-providers:  
  speedtest / Domain: {<<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/speedtest.mrs"}  
  Github / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/github.mrs"}  
  Telegram / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/telegram.mrs"}
  Twitter / Domain: {<<: *domain, url: "https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs"}
  Youtube / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/youtube.mrs"}
  Google / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/google.mrs"} 
  Google-play / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/google-play.mrs"}
  GoogleVoice / Domain: {<<: *class, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/list/GoogleVoice.list"}
  Netflix / Domain: {<<: *domain, url: "https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"} 
  cloudflare / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/cloudflare.mrs"}
  Proxy / Domain: {<<: *class, url: "https://raw.githubusercontent.com/LaoShaYang/clash/refs/heads/main/meta-rules-dat/geo/list/Proxy.list"}
  Globe / Domain: {<<: *class, url: "https://raw.githubusercontent.com/LaoShaYang/clash/refs/heads/main/meta-rules-dat/geo/list/Global.list"} 
  Direct / Domain: {<<: *class, url: "https://raw.githubusercontent.com/LaoShaYang/clash/refs/heads/main/meta-rules-dat/geo/list/Direct.list"}
  ChinaMedia / Domain: {<<: *class, url: "https://raw.githubusercontent.com/LaoShaYang/clash/refs/heads/main/meta-rules-dat/geo/list/ChinaMedia.list"} 
  China / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/cn.mrs"}  
  Private / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/private.mrs"}
  Block / Domain: {<<: *class, url: "https://raw.githubusercontent.com/LaoShaYang/clash/refs/heads/main/meta-rules-dat/geo/list/Block.list"}
  
  cloudflare / IP: {<<: *ip, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geoip/cloudflare.mrs"}
  Telegram / IP: {<<: *ip, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geoip/telegram.mrs"}
  Google / IP: {<<: *ip, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geoip/google.mrs"}
  Netflix / IP: {<<: *ip, url: "https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  China / IP: {<<: *ip, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geoip/cn.mrs"}
  
#  GateFireWall / Domain: {<<: *domain, url: "https://github.com/LaoShaYang/clash/raw/refs/heads/main/meta-rules-dat/geo/geosite/gfw.mrs"}